name: mecab_for_dart
description: Dart plugin which provides binding to Mecab library (Japanese Morphological Analyzer)
version: 2.0.0
homepage:
  https://github.com/captaindario/mecab_for_dart
funding:
  - https://github.com/sponsors/CaptainDario
  - https://buymeacoffee.com/dariyooo
  - https://patreon.com/DaAppLab

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  universal_ffi: ^1.1.0
  universal_io: ^2.2.2
  hooks: ^1.0.1
  code_assets: ^1.0.0
  native_toolchain_c: ^0.17.0

dev_dependencies:
  import_sorter: ^4.6.0
  test: ^1.25.14

platforms:
  android:
  ios:
  windows:
  linux:
  macos:
  web:

